PracticaMVC/Controllers/CaminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using PracticaMVC.Models;
using System.Net;

namespace PracticaMVC.Models.Extend
{
    public class CaminController : Controller
    {
        public ActionResult Index()
        {
            CaminEntities db = new CaminEntities();

            var camin = from a in db.Camin select a;

            camin = db.Camin.OrderBy(a => a.ID);

            return View(camin);
        }

        public ActionResult TeamDetails(int? id)
        {
            CaminEntities db = new CaminEntities();

            if (id == null)
            {
                return HttpNotFound();
            }
            Camin camin = db.Camin.Include(t => t.Studenti).Include(t => t.Camere).Include(t => t.Asezare).FirstOrDefault(t => t.ID == id);
            if (camin == null)
            {
                return HttpNotFound();
            }
            return View(camin);
        }

        public ActionResult Edit(int? id)
        {
            CaminEntities db = new CaminEntities();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Asezare asezare = db.Asezare.Find(id);

            if (asezare == null)
            {
                return HttpNotFound();
            }
            return View(asezare);
        }

        [HttpPost]
        public ActionResult Edit(Asezare asezare)
        {
            CaminEntities db = new CaminEntities();

            if (ModelState.IsValid)
            {
                db.Entry(asezare).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("TeamDetails/" + asezare.Camin_ID);
            }
            return View(asezare);
        }

        public ActionResult PartialToEdit()
        {
            return PartialView();
        }
    }
}

PracticaMVC/Views/Shared/DisplayCamera.cshtml
@model PracticaMVC.Models.Camere

<option value="">--Selectati Camera--</option>

@if(ViewBag.CameraID != null)
{
    foreach(var item in ViewBag.CameraID)
    {
        <option value="@item.Value">@item.Text</option>
    }
}

PracticaMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CaminMVC</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" />
    @*<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <div class="navbar navbar-nav navbar-left">
                    @if (@User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Salut " + @User.Identity.Name, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Lista Caminelor", "Index", "Camin", new { area = "" }, new { @class = "navbar-brand" })
                    }

                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @if (@User.Identity.IsAuthenticated)
                        {
                            <a href="@Url.Action("Logout", "Auth")" class="navbar-brand">Iesire</a>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div class="nav navbar" style="display:block;">
            <div id="img" style="margin-right:550px;">
                <a href="@Url.Action("Index", "Home")">
                    <img src="~/images/logo.jpg" style="width:500px; height:100px; margin-top:50px;" />
                </a>
            </div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - CaminMvc</p>
        </footer>
    </div>


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>